language: go
sudo: false

go:
  - 1.7

install:
    - go get -d -v ./... && go build -v ./...
    - go get github.com/gin-gonic/contrib/sessions
    - go get github.com/gin-gonic/gin
    - go get github.com/mattn/go-sqlite3
    - go get github.com/pkg/sftp
    - go get golang.org/x/crypto/ssh
    - go get gopkg.in/gcfg.v1
